version: "3.7"
services:
  ldap:
    image: rroemhild/test-openldap
    ports:
     - "10389:10389"
  keycloak3:
    image: quay.io/keycloak/keycloak:21.0.1
    container_name: keycloak
    ports:
     - "8080:8080"
    environment:
     - KEYCLOAK_ADMIN=admin 
     - KEYCLOAK_ADMIN_PASSWORD=admin    
    extra_hosts:
     - "host.docker.internal:host-gateway"   
    command:
      - start-dev     